# 3a

In [15]:
import re

def function3b(text_string):

    pattern = r"mul\(\d+,\d+\)"

    matches = re.findall(pattern, text_string)

    result = []

    for i in matches:

        pattern = r"\d+"

        items = []

        items.extend(re.findall(pattern, i))

        items_int = [int(item) for item in items]

        result.append(items_int[0]*items_int[1])

    return sum(result)

    

In [16]:
file_name = "Inputs\\input_03.txt"

text_string = []

with open(file_name, 'r') as file:

    text_ = file.read()

    text_string.append(text_)

text_string = ''.join(text_string)

function3b(text_string)

170778545

# 3b

In [17]:
import re

def find_occurrences(text, target_string):
    matches = [match.start() for match in re.finditer(re.escape(target_string), text)]
    return matches

# Example usage
long_text = """This is a sample text. Text occurs multiple times. Find all text occurrences in this text."""
target = "text"

occurrences = find_occurrences(long_text, target)
print(f"Occurrences of '{target}' found at positions: {occurrences}")


Occurrences of 'text' found at positions: [17, 60, 85]


In [18]:
import re
import pandas as pd

dict = {
    'type':['do'],
    'location': [0],
    'id': [0]
}

dos = find_occurrences(text_string, 'do()')

donts = find_occurrences(text_string, "don't()")

for i,location in enumerate(dos):

    dict['location'].append(location)
    dict['type'].append('do')
    dict['id'].append(i+1)

for i,location in enumerate(donts):

    dict['location'].append(location)
    dict['type'].append(f'dont')
    dict['id'].append(i)

result = pd.DataFrame(dict)

result_sorted = result.sort_values(by='location')

result_sorted.reset_index(inplace=True)

result_sorted

text_string

chars = {
    'location':[],
    'char':[]
}

for i,char in enumerate(text_string):

    chars['location'].append(i)
    chars['char'].append(char)

df_chars = pd.DataFrame(chars)

df_chars_merged = df_chars.merge(result_sorted, how='left', on='location')

cols = ['location','char','type']

df_chars_merged_ffill = df_chars_merged[cols].ffill()

df = df_chars_merged_ffill.copy()

df_list = df.loc[df['type'] == 'do', 'char'].to_list()

df_string = ''.join(df_list)

df_string

function3b(df_string)


82868252




    

82868252

# 4a

In [19]:
import re
import numpy as np

file_name = "Inputs\\input_04.txt"

occurrences = []

with open(file_name, 'r') as file:

    lines = file.readlines()

    rows = []

    for i in lines:

        line = i

        chars = []

        for j in list(range(len(line)-1)):

            chars.append(line[j])

        rows.append(chars)

matrix = np.array(rows)

matrix



array([['M', 'X', 'X', ..., 'S', 'X', 'S'],
       ['S', 'A', 'S', ..., 'M', 'A', 'A'],
       ['M', 'A', 'S', ..., 'M', 'X', 'M'],
       ...,
       ['M', 'S', 'M', ..., 'S', 'M', 'M'],
       ['A', 'S', 'A', ..., 'A', 'A', 'X'],
       ['S', 'M', 'A', ..., 'M', 'M', 'M']], shape=(140, 140), dtype='<U1')

In [20]:
#columns

occurrences = []

for i in list(range(len(matrix))):

    row = ''.join(matrix[i])

    column = ''.join(matrix.T[i])

    occurrences.extend(find_occurrences(row, 'XMAS'))
    occurrences.extend(find_occurrences(row[::-1], 'XMAS'))
    occurrences.extend(find_occurrences(column, 'XMAS'))
    occurrences.extend(find_occurrences(column[::-1], 'XMAS'))


len(occurrences)



860

In [21]:
# diagonals

diags = []

for x in list(range(len(matrix[0]))):

    y = 0

    diag = []

    while x < len(matrix[0]):

        diag.append(str(matrix[y][x]))

        x = x + 1
        y = y + 1

    #print(diag)

    diags.append(''.join(diag))

for y in list(range(1,len(matrix))):

    x = 0

    diag = []

    while y < len(matrix):

        diag.append(str(matrix[y][x]))

        x = x + 1
        y = y + 1

    #print(diag)

    diags.append(''.join(diag))

for x in list(range(len(matrix[0])))[::-1]:

    y = 0

    diag = []

    while x >= 0:

        diag.append(str(matrix[y][x]))

        x = x - 1
        y = y + 1

    #print(diag)

    diags.append(''.join(diag))

for y in list(range(1,len(matrix)))[::-1]:

    x = len(matrix[0])-1

    diag = []

    while y < len(matrix):

        diag.append(str(matrix[y][x]))

        x = x - 1
        y = y + 1

    #print(diag)

    diags.append(''.join(diag))

for i in diags:

    occurrences.extend(find_occurrences(i[::-1], 'XMAS'))
    occurrences.extend(find_occurrences(i, 'XMAS'))

len(occurrences)


2530

# 4b

In [22]:
diags = {
    'x':[],
    'y':[],
    'char':[],
    'start_coords': [],
    'step': []
}

for x in list(range(len(matrix[0]))):

    y = 0

    diag = []

    start_coords = f'{x},{y}'

    step = '+1+1'

    while x < len(matrix[0]):

        char = str(matrix[y][x])

        diags['x'].append(x)
        diags['y'].append(y)
        diags['char'].append(char)
        diags['start_coords'].append(start_coords)
        diags['step'].append(step)

        x = x + 1
        y = y + 1

for y in list(range(1,len(matrix))):

    x = 0

    diag = []

    start_coords = f'{x},{y}'

    step = '+1+1'

    while y < len(matrix):

        char = str(matrix[y][x])

        diags['x'].append(x)
        diags['y'].append(y)
        diags['char'].append(char)
        diags['start_coords'].append(start_coords)
        diags['step'].append(step)

        x = x + 1
        y = y + 1

for x in list(range(len(matrix[0])))[::-1]:

    y = 0

    diag = []

    start_coords = f'{x},{y}'

    step = '-1+1'

    while x >= 0:

        char = str(matrix[y][x])

        diags['x'].append(x)
        diags['y'].append(y)
        diags['char'].append(char)
        diags['start_coords'].append(start_coords)
        diags['step'].append(step)

        x = x - 1
        y = y + 1

for y in list(range(1,len(matrix)))[::-1]:

    x = len(matrix[0])-1

    diag = []

    start_coords = f'{x},{y}'

    step = '-1+1'

    while y < len(matrix):

        char = str(matrix[y][x])

        diags['x'].append(x)
        diags['y'].append(y)
        diags['char'].append(char)
        diags['start_coords'].append(start_coords)
        diags['step'].append(step)

        x = x - 1
        y = y + 1
   

df_diags = pd.DataFrame(diags)

df_id = df_diags.copy()

cols = ['start_coords', 'step']

df_id = df_id[cols]

df_id = df_id.drop_duplicates().reset_index()

df_id['id'] = df_id.index

df_merged = df_diags.merge(df_id, how='left', on=['start_coords','step'])

cols = ['x','y','char','start_coords','step','id']

df_merged = df_merged[cols]

In [23]:
df_plus = df_merged.copy()

df_plus = df_plus[df_plus['step'] == '+1+1']

df_minus = df_merged.copy()

df_minus = df_minus[df_minus['step'] == '-1+1']

df = df_plus.merge(df_minus[['x','y','id']], how='left', on=['x','y'])

dict = {
    'diag_id':[],
    'coord':[],
    'concat_chars':[],
}

unique_ids = df['id_x'].drop_duplicates().to_list()

for id in [2]:

    diag = df[df['id_x'] == id]

    for i in list(range(len(diag))):

        char = diag[diag['id_x']==i]['char']

        if char == 'A':

            prev_char = diag.loc[i-1, 'char']
            next_char = diag.loc[i+1, 'char']
            x_ = diag.loc[i, 'x']
            y_ = diag.loc[i, 'y']
            coord = f'{x_},{y_}'
            concatenated_chars = f'{prev_char}{char}{next_char}'

            if concatenated_chars in ['MAS','SAM']:

                dict['diag_id'].append(id)
                dict['coord'].append(coord)
                dict['concat_chars'].append(concatenated_chars)



        



ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [191]:
diag

x    y char start_coords  step  id_x  id_y
279    2    0    X          2,0  +1+1     2   416
280    3    1    A          2,0  +1+1     2   414
281    4    2    S          2,0  +1+1     2   412
282    5    3    M          2,0  +1+1     2   410
283    6    4    X          2,0  +1+1     2   408
..   ...  ...  ...          ...   ...   ...   ...
412  135  133    S          2,0  +1+1     2   429
413  136  134    A          2,0  +1+1     2   427
414  137  135    M          2,0  +1+1     2   425
415  138  136    X          2,0  +1+1     2   423
416  139  137    M          2,0  +1+1     2   421

[138 rows x 7 columns]

In [195]:
df_plus = df_merged.copy()

df_plus = df_plus[df_plus['step'] == '+1+1']

df_minus = df_merged.copy()

df_minus = df_minus[df_minus['step'] == '-1+1']

df = df_plus.merge(df_minus[['x','y','id']], how='left', on=['x','y'])

dict = {
    'diag_id':[],
    'coord':[],
    'concat_chars':[],
}

unique_ids = df['id_x'].drop_duplicates()

for id in [2]:

    diag = df[df['id_x'] == id]

    for i in list(range(len(diag))):

        char = diag[diag['id_x']==i]['char']

        if char == 'A':

            prev_char = diag.loc[i-1, 'char']
            next_char = diag.loc[i+1, 'char']
            x_ = diag.loc[i, 'x']
            y_ = diag.loc[i, 'y']
            coord = f'{x_},{y_}'
            concatenated_chars = f'{prev_char}{char}{next_char}'

            if concatenated_chars in ['MAS','SAM']:

                dict['diag_id'].append(id)
                dict['coord'].append(coord)
                dict['concat_chars'].append(concatenated_chars)

    break

df_result = pd.DataFrame(dict)

df_result



ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [149]:
df_plus = df_merged.copy()

df_plus = df_plus[df_plus['step'] == '+1+1']

df_minus = df_merged.copy()

df_minus = df_minus[df_minus['step'] == '-1+1']

df_merged = df_plus.merge(df_minus[['x','y','id']], how='left', on=['x','y'])

dict = {
    'diag_id':[],
    'coord':[],
    'concat_chars':[],
}

for id in df_merged['id_x']:

    diag = df_merged[df_merged['id_x'] == id]

    for i in list(range(len(diag))):

        char = diag.loc[i, 'char']

        if char == 'A':

            prev_char = diag.loc[i-1, 'char']
            next_char = diag.loc[i+1, 'char']
            x_ = diag.loc[i, 'x']
            y_ = diag.loc[i, 'y']
            coord = f'{x_},{y_}'
            concatenated_chars = f'{prev_char}{char}{next_char}'

            if concatenated_chars in ['MAS','SAM']:

                dict['diag_id'].append(id)
                dict['coord'].append(coord)
                dict['concat_chars'].append(concatenated_chars)

    break

df_result = pd.DataFrame(dict)

df_result

KeyError: "['id'] not in index"

In [ ]:
occurrences = []

diags = []

for x in list(range(len(matrix[0]))):

    y = 0

    diag = []

    while x < len(matrix[0]):

        diag.append(str(matrix[y][x]))

        x = x + 1
        y = y + 1

    #print(diag)

    diags.append(''.join(diag))

for y in list(range(1,len(matrix))):

    x = 0

    diag = []

    while y < len(matrix):

        diag.append(str(matrix[y][x]))

        x = x + 1
        y = y + 1

    #print(diag)

    diags.append(''.join(diag))

for x in list(range(len(matrix[0])))[::-1]:

    y = 0

    diag = []

    while x >= 0:

        diag.append(str(matrix[y][x]))

        x = x - 1
        y = y + 1

    #print(diag)

    diags.append(''.join(diag))

for y in list(range(1,len(matrix)))[::-1]:

    x = len(matrix[0])-1

    diag = []

    while y < len(matrix):

        diag.append(str(matrix[y][x]))

        x = x - 1
        y = y + 1

    #print(diag)

    diags.append(''.join(diag))

for i in diags:

    occurrences.extend(find_occurrences(i[::-1], 'MAS'))
    occurrences.extend(find_occurrences(i, 'MAS'))





In [24]:
# New approach

matrix

array([['M', 'X', 'X', ..., 'S', 'X', 'S'],
       ['S', 'A', 'S', ..., 'M', 'A', 'A'],
       ['M', 'A', 'S', ..., 'M', 'X', 'M'],
       ...,
       ['M', 'S', 'M', ..., 'S', 'M', 'M'],
       ['A', 'S', 'A', ..., 'A', 'A', 'X'],
       ['S', 'M', 'A', ..., 'M', 'M', 'M']], shape=(140, 140), dtype='<U1')

In [ ]:
import numpy as np

# Generate a 9x9 matrix with sequential numbers
#matrix = np.arange(1, 50).reshape(7, 7)
#print(matrix)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]
 [29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42]
 [43 44 45 46 47 48 49]]


In [33]:
import numpy as np

# Generate a 9x9 matrix with sequential numbers
#matrix = np.arange(1, 82).reshape(9, 9)
#print(matrix)

x_mas = []

for i in list(range(len(matrix[0])-2)):

    for j in list(range(len(matrix)-2)):

        sqr = matrix[j:j+3,i:i+3]

        flattened_list = sqr.flatten().tolist()

        if flattened_list[4] == 'A':

            if (flattened_list[0] == 'M' and flattened_list[8] == 'S') or (flattened_list[0] == 'S' and flattened_list[8] == 'M'):

                if (flattened_list[2] == 'M' and flattened_list[6] == 'S') or (flattened_list[2] == 'S' and flattened_list[6] == 'M'):
    
                    x_mas.append(flattened_list)


len(x_mas)


1921